# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The University of New Hampshire Programming Club (Official)
email: klmiller1@wildcats.unh.edu
description: Updates from the University of New Hampshire Programming Club
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  unhm-programming-club
google_analytics: true

# test for themes if desired by uncommenting this
# show_downloads: true

# Build settings
theme: minima
alternate_themes:
  - chipset
  - karl-custom-1
  - minima-solarized
  - minima-dark
  - minima-solarized-dark
  - architect
  - cayman
  - dinky
  - hacker
  - leap-day
  - merlot
  - midnight
  - minimal
  - modernist
  - tactile
  - time-machine
plugins:
  - jekyll-feed

collections:
  - authors

# added as <links> in the top after the regular stylesheet in head include
component_styles:
  - menuButton
  - popoutMenu

# footer scripts - added after <footer> in footer.html in this order:

settings_button: true 
conways: true
theme_selector: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
